export const ADD_TOAST = 'ADD_TOAST';
export const REMOVE_TOAST = 'REMOVE_TOAST';
export const TOAST_TYPE = {
  SMALL: 'TOAST_SMALL',
  MEDIUM: 'TOAST_MEDIUM',
  LARGE: 'TOAST_LARGE',
};
export const TOAST_POSITION = {
  TOP_LEFT: 'TOP_LEFT',
  TOP_RIGHT: 'TOP_RIGHT',
  TOP_MIDDLE: 'TOP_MIDDLE',
  BOTTOM_LEFT: 'BOTTOM_LEFT',
  BOTTOM_RIGHT: 'BOTTOM_RIGHT',
  BOTTOM_MIDDLE: 'BOTTOM_MIDDLE',
};
