os: unstable

# cache yarn and node_modules folder for rebuilds
cache:
  - "%LOCALAPPDATA%\\Yarn"
  - node_modules

# The environment configurations. We will use the latest node version.
environment:
  # the token is encrypted by appveyor. No need to hide it.
  GH_TOKEN:
    secure: iCb7rTARh54Z2o91jMgIsjvUn0zrJUXoMOG9nDAZ6vZB+5L+KrNKk2v6B6SUKvt7
  matrix:
    - NODE_VERSION: 7

# make sure we are running on 64bit
platform:
  - x64

# if one build fails, fail all builds.
matrix:
  fast_finish: true

# we only need node (64bit) and yarn (preinstalled)
install:
  - ps: Install-Product node $env:NODE_VERSION x64
  - set CI=true
  - yarn install

test_script:
  - yarn ci:all

build: off

# only deploy on success and if we are on the master branch
on_success:
  - IF %APPVEYOR_REPO_BRANCH%==master yarn ci:deploy
